# docker-compose.yml
version: '3.3'

name: ioffer
services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 3306:3306
    tty: true
    volumes:
      - /Volumes/LocalIO/DATABASE/docker-data/mysql-run:/var/run/mysqld
      - /Volumes/LocalIO/DATABASE/docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spree_development
      MYSQL_USER: deploy
      MYSQL_PASSWORD: deploy123
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
  redis:
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379
    tty: true
    volumes:
      - ./doc/config/redis.conf.development:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Volumes/LocalIO/DATABASE/docker-data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    tty: true
  rails:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    command: /bin/sh -c "rm -f /var/www/shoppn_spree/tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=spree_development
      - MYSQL_USER=deploy
      - MYSQL_PASSWORD=deploy123
      - RAILS_ENV=development
    ports:
      - 8000:8000
    tty: true
    volumes:
      - mysql_store:/var/run/mysqld
      - ./:/var/www/shoppn_spree
      - bundler_gems:/usr/local/bundle/
      - assets_store:/var/www/shoppn_spree/public/
volumes:
  bundler_gems:
  assets_store:
  mysql_store:
  mysql_data:
  esdata:
    driver: local