development:
  adapter: mysql2
  database: ioffer_development
  username: deploy
  password: deploy123
  host: mysql
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

test:
  adapter: mysql2
  database: ioffer_test
  username: deploy
  password: deploy123
  host: mysql
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  adapter: mysql2
  database: ioffer_production
  username: deploy
  password: deploy123
  host: mysql
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
